---
title: "HW1"
author: "Christakakis - aid23004"
date: "2022-10-19"
output: 
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-packages, include=FALSE}
library(dplyr)
library(tidyverse)
```

## [ΜΕΡΟΣ Α]

```{r import data, echo=TRUE}
data <- tribble(
 ~happy, ~uptempo, ~blues, ~jazz, ~gospel,
 "yes", "yes", 10, 5, 20,
 "no", "no", NA, 12, 15,
 "yes", "no", 7, 6, 4,
 "no", "yes", 3, NA, NA
)
data
```

**(α)**

```{r a}
data_tidy1 <- data %>%
	gather(key = "genre", value = "count", -happy, -uptempo)
data_tidy1
```

**(β)**

```{r b}
data_tidy2 <- na.omit(data_tidy1)
data_tidy2
```

**(γ)**

```{r c.1}
data_tidy3 <- tribble(
    ~jazz, ~happy,
    "FALSE", "FALSE",
    "FALSE", "TRUE",
    "TRUE", "FALSE",
    "TRUE", "TRUE",
)
data_tidy3
```

```{r c.2}
data_tidy3 <- mutate(data_tidy3, total = 0)
data_tidy3
```

```{r c.3}
false_false <- data_tidy2 %>%
	filter(happy == "no" & genre != "jazz")
data_tidy3[1,3] <- sum(false_false$count)
false_false
```

```{r c.4}
false_true <- data_tidy2 %>%
	filter(happy == "yes" & genre != "jazz")
data_tidy3[2,3] <- sum(false_true$count)
false_true
```

```{r c.5}
true_false <- data_tidy2 %>%
	filter(happy == "no" & genre == "jazz")
data_tidy3[3,3] <- sum(true_false$count)
true_false
```

```{r c.6}
true_true <- data_tidy2 %>%
	filter(happy == "yes" & genre == "jazz")
data_tidy3[4,3] <- sum(true_true$count)
true_true
```

```{r c.7}
data_tidy3
```

**(δ)**

```{r d.1}
sum(data_tidy2[which(data_tidy2$happy == "no" & data_tidy2$genre == 'jazz'),4])
```

```{r d.2}
data_tidy3[which(data_tidy3$happy == "FALSE" & data_tidy3$jazz == 'TRUE'),3]
```

## [ΜΕΡΟΣ Β]

```{r load}
library(tidyverse)
who <- tidyr::who
dict_url <- "https://extranet.who.int/tme/generateCSV.asp?ds=dictionary"
if (!file.exists("dict.csv")) download.file(dict_url, "dict.csv")
dict <- read_csv('dict.csv')
labels <- data.frame(name = colnames(who))
explanations <- semi_join(dict, labels, by=c("variable_name" = "name"))
```

**(1)** 

```{r 1}
who <- who %>%
	gather(key = "notification", value = "cases", -country, -iso2, -iso3, -year)
who <- na.omit(who)
who
```

**(2)**

```{r 2}
who$notification <- str_replace(who$notification, "newrel", "new_rel")
tail(who)
```

**(3)**

```{r 3}
B <- tidyr::separate(who, notification, into = c("new", "age"), "(?<=[a-z])(?=[0-9])")
B <- tidyr::separate(B, new, into = c("new", "type", "sex"), "_")
who <- B
who
```

**(4)**

```{r 4}
who <- select(who, -new, -iso2, -iso3)
who
```

**(5)** 

```{r 5}
C <- who %>% group_by(country) %>% summarize(count = sum(cases))
C
```

**(6)** 

```{r 6}
D <- who %>%
	filter(type == "sp") %>%
	group_by(year) %>%
	slice(which.max(cases)) %>%
	select(-type, -sex, -age)

D <- D[,c(2,1,3)]
D
```

**(7)** 

```{r 7}
E <- who %>%
	filter(country == "Greece") %>%
	select(-type, -age, -country) %>%
	group_by(year,sex) %>%
	summarize(cases = sum(cases)) %>%
	pivot_wider(names_from = sex, values_from = cases) %>%
	arrange(desc(f), desc(m))
E
```
